### ISSUE TITLE
Sample text smaller than the supposed "minimum input size"

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/personality-insights-nodejs#15]
The demo claims to require 3500 words and then provides a sample input with 1341 unique words. I understand the reasons for displaying deliberately incorrect input size requirements, but if we're going to do that we should at least provide a sample input that meets the stated fake size requirements.

**Comment by germanattanasio** [comment]
fixed in b168143290376df9d473fdfc80319e6c92151ca2

**Comment by jschoudt** [comment]
Still an issue with Spanish.  Working on getting a new sample for spanish approved.

**Comment by germanattanasio** [comment]
:+1:

**Comment by germanattanasio** [comment]
@arypbatista are we going to provide sample text in spanish?

**Comment by arypbatista** [comment]
I don't know how this resulted in this selection of sample texts... I will propose a new sample text for Spanish. For now that are the legally approved sample texts.

**Comment by germanattanasio** [comment]
The new demo doesn't have an spanish sample text so I'm closing this.
